"""add subtitles to article model

Revision ID: 6df0fdfa8a0a
Revises: 98d0257c7247
Create Date: 2023-03-26 22:10:34.136355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6df0fdfa8a0a'
down_revision = '98d0257c7247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtitle', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('subtitle')

    # ### end Alembic commands ###
