"""article category model

Revision ID: 7e635206b463
Revises: 74db66b4fd82
Create Date: 2023-03-27 11:50:10.034323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e635206b463'
down_revision = '74db66b4fd82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_category',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], name='fk_article_id'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='fk_category_id'),
    sa.PrimaryKeyConstraint('article_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_category')
    # ### end Alembic commands ###
