"""add foreign key in model article

Revision ID: 826e442ad6f2
Revises: e8eaf3a15f1f
Create Date: 2023-03-26 22:20:39.050106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '826e442ad6f2'
down_revision = 'e8eaf3a15f1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
