"""add foreign key in model articl

Revision ID: c416be5b02c4
Revises: 826e442ad6f2
Create Date: 2023-03-26 22:37:50.778859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c416be5b02c4'
down_revision = '826e442ad6f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('my_constraint_name', sa.Integer(), server_default='some_default_value', nullable=True))
        batch_op.create_foreign_key(None, 'user', ['my_constraint_name'], ['id'])
        batch_op.drop_column('subtitle')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtitle', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('my_constraint_name')

    # ### end Alembic commands ###
