"""remove subtitle from aritcle model

Revision ID: e8eaf3a15f1f
Revises: 6df0fdfa8a0a
Create Date: 2023-03-26 22:12:06.876016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8eaf3a15f1f'
down_revision = '6df0fdfa8a0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('subtitle')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtitle', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
